### PR TITLE
Add Batterry Buzzer to the PDB and correct issue of connector. 

### PR DESCRIPTION
**Pull request by Mohammed0987**
Please double check that the stop masks are not a problem. Run DRC on it. Also double check the silkscreen and electrical style guidelines.

### CODE REVIEW

**Comment by Mohammed0987** [comment]
Also merge both sch and brd

**Comment by dHutchings** [comment]
Alright.  Some comments here:
1. My version of eagle says that there are still 3 unrouted connections.  (You see a number on the bottom right when you run "ratsnest").

It looks like that two of them are where the bottom layer connections are trying to be connected to the top, but there are no vias between the top and the bottom layer.
1. We've got some trace width problems.  Specifically:
   -The BAT trace is only 47 mil wide.
   -The 12V Trace to the Regulator.
   -The 5V trace to the ground plane.

We need much larger traces / planes for these high power connections.  Consult a PCB trace width calculator.  You'll need much, much wider traces / use ground planes.  It'd be best to get some better / more complex ground planes.

This may be partially caused by the XT60 connector and the JST connector being right right next to each other.  They can be moved a bit apart.  You'll have the room if the XT60 connector moves a little towards the bottom right.
1. Update your library.  According to seiya:
   "also he didn't update his library.  if you go to top, Library > Update All, a lot of things change in the brd"
2.  Let's keep JP2 near the outer perimeter of the board.  It's just a debugging feature.  It's there so that if we need to hook an oscilliscope up to the board, we can solder in headers for the ground clip for the scope.
3.  A lot of the complexity of your routing near the Battery Buzzer is caused by having to route a singularly complex Ground Trace.  It'd make it a lot easier for you to small ground plane on the top near the battery buzzer.
4.  Stop mask errors.  Don't worry about them, that'll get fixed by the manufacturer.
5.  Connector placement.  Good job keeping the USB connector pointing out for the arduino mirco.  Maybe maybe could we do the same thing with the XT60 / JST?  Keep them on the perimeter instead of the center?  If you can't, don't kill yourself doing this.

Keep it up!  It's going well.

**Comment by dHutchings** [comment]
Updated comments.  Two sections of comments: Critical (For board order, must be fixed), and "Would be nice"

Critical:
-A drill, U$3, is currently placed at 0.4 x 5.1, off the edge of the board.  it either must be moved onto the board or removed.
-Need to fix the fact that there are two board files (PDB.brd and PDB_MH.brd, but only one schematic file.)  Forward/ Back annotation is broken, which is very not good.  The wrong version could accidentally get ordered.
-The XT60 connector needs to be re-oriented.  In its current position / location, there is very little copper carrying the return current to the battery.  (Approx .3 inches)  A change of how the 5V line on the bottom of the PCB is routed could probably also accomplish this goal.
-JP2 needs to be moved to the edge of the board.

Would be nice:
-The frame on second page of schematic needs to be fixed.  (updated with correct info)
-It's not ideal to have a bolt hole in the middle of the high current power plane.  (u$5)
-There's a lot of overlapping silkscreen.  Could use some work to cleanup, but this can def wait till rev c.  The silkscreen could stand to be much cleaner, and have the high-precision resistors explicitly labeled as such.  (View the battery buzzer for a good example)
-Could be smaller.  This could possibly be achieved w/ better routing of the buzzer section
-The polygon carrying Bat+ is not square.  It's not parallel to the x-axis.  Several of the other polygons are also not straight (to lesser degrees).
-Silkscreen labels that explain the function of the buttons would be good.
-Silkscreen labels on the fuses aren't symmetric.

**Comment by tobinsarah** [comment]
There is an extra mounting hole above the board that should be deleted.... that's covered by Doug's comment.

**Comment by tobinsarah** [comment]
The mounting hole U$5 is still in the middle of the BAT power plane. I would try moving it to the left, next to the resistors (you may need to reroute BCELL3 trace).

Also, I'm concerned that the BAT polygon is too narrow near the DPST_SWITCH. I would make it wider by moving up the bottom edge of the 5V plane, so you can make the BAT plane wider below it. Like this:  
screen shot 2016-10-30 at 10 36 04 pm

(NOTE: there is a small 5V trace with a via that may need to be moved up as well)

**Comment by Mohammed0987** [comment]
I dont think there is a U$5.

**Comment by onibrow** [comment]
Is this done? If so we can merge :-))

**Comment by Mohammed0987** [comment]
I believe so.

**Comment by tobinsarah** [comment]
The current schematic file that is in the repo does no include the battery buzzer components. We need to find the correct version of the schematic and replace it in the repo.

**Pull request merged**
